INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('OSD', 'Office of Student Development');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('SRRL', 'Office of Student Resources and Residential Life');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('CAPS', 'Office of Careers and Placement Services');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('OCW', 'Office of Counselling and Wellness');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('OGUR', 'Office of General University Requirements');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('OSL', 'Office of Service-Learning');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('IC', 'Industrial Centre');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('ITS', 'Information Technology Services Office');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('LIB', 'Pao Yue-kong Library');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('AS', 'Academic Secretariat');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('UHS', 'University Health Service');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('ABCT', 'Department of Applied Biology and Chemical Technology');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('AMA', 'Department of Applied Mathematics');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('AP', 'Department of Applied Physics');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('ITC', 'Institute of Textiles and Clothing');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('AF', 'School of Accounting and Finance');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('LMS', 'Department of Logistics and Maritime Studies');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('MM', 'Department of Management and Marketing');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('BRE', 'Department of Building and Real Estate');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('BSE', 'Department of Building and Service Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('CEE', 'Department of Civil and Environmental Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('LSGI', 'Department of Land Surveying and Geo-Informatics');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('COMP', 'Department of Computing');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('EE', 'Department of Electrical Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('EIE', 'Department of Electronic and Information Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('ISE', 'Department of Industrial and Systems Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('ME', 'Department of Mechanical Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('DD', 'Interdisciplinary Division of Aeronautical and Aviation Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('IDBE', 'Interdisciplinary Division of Biomedical Engineering');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('APSS', 'Department of Applied Social Sciences');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('HTI', 'Department of Health Technology and Informatics');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('RS', 'Department of Rehabilitation Sciences');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('SN', 'School of Nursing');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('SO', 'School of Optometry');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('CBS', 'Department of Chinese and Bilingual Studies');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('CC', 'Department of Chinese Culture');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('ENGL', 'Department of English');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('CIHK', 'Confucius Institute of Hong Kong');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('ELC', 'English Language Centre');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('GEC', 'General Education Centre');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('SD', 'School of Design');
INSERT INTO "USER_NAME".DEPT_ABBR_INFO ("DeptAbbr", "Name") VALUES ('SHTM', 'School of Hotel and Tourism Management');