INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (103, 'Sleep assistant', 'Help others to sleep', 70, 8, 1, 7, 'N', 4, 'Y', 3, 0, 'Y', TO_DATE('2017-12-05 06:33:05', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-25 23:59:59', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (81, 'Lab Assistant', 'Roles & Responsibilities
    Assist lab experiment

Requirements
    Good Communication skills
    Good lab skills', 70, 12, 1, 11, 'Y', 4, 'Y', 2, 8, 'Y', TO_DATE('2017-11-30 19:04:41', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (83, 'Student Assistant', 'ellentesque suscipit eros sit amet risus porta, vitae euismod dolor fringilla. Donec placerat velit in laoreet semper. Vestibulum maximus in magna vel accumsan. Phasellus id dui dui. Sed auctor aliquet libero, nec rutrum orci ultrices elementum. Mauris congue metus imperdiet massa scelerisque, in semper libero tempor. Donec eleifend nisl quis elit porttitor finibus.', 60, 11, 1, 9, 'Y', 10, 'N', 2, 26, 'Y', TO_DATE('2017-11-30 22:56:47', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-30 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (0, 'Student Assistant', 'Roles & Responsibilities
    Reception, data entry and activity support. Outdoor work may be required on occasion.
    Graphic and website design
    Video production
    Any other duties as assigned
    DRESS SOME DRESS

Requirements
    Good Communication skills
    Good design, video production and /or I.T skills being an added advantage', 70, 6, 1, 5, 'N', 66, 'Y', 2, 0, 'Y', TO_DATE('2017-12-04 17:46:25', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-29 00:00:01', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (82, 'A ordinary job', 'In aliquet aliquam posuere. Aliquam vitae ex nisl. Pellentesque sollicitudin nisl vitae nunc gravida consectetur. Vivamus lacus lectus, condimentum vel urna vel, congue commodo dui. Sed eu tempor elit, et pharetra augue. Vestibulum enim enim, cursus vel velit quis, condimentum placerat libero. Vestibulum posuere imperdiet cursus. Nunc ac diam lectus. Nulla vitae nisl purus. ', 1000, 3, 1, 6, 'Y', 100, 'N', 1, 8, 'N', TO_DATE('2017-10-26 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2015-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (84, 'A job', 'Cras euismod euismod orci, non blandit tortor convallis quis. Curabitur interdum at magna ac posuere. Aliquam mollis dolor at purus ultrices pharetra. In sed orci commodo, maximus nunc eu, imperdiet nisi. Curabitur nec viverra nulla. Fusce id erat non metus viverra porttitor.', 100, 10, 2, 10, 'Y', 10, 'Y', 3, 15, 'Y', TO_DATE('2017-12-01 18:11:47', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2015-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (85, 'real', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse dolor nibh, convallis at fringilla pretium, aliquam eget risus. Vestibulum eu arcu nec sem egestas accumsan sit amet ut quam. Etiam placerat, sapien in cursus imperdiet, augue erat rutrum metus, vel vulputate odio ex ut velit. Duis ut eros sapien. Praesent in dui massa. Donec vehicula feugiat mollis. Nullam eget velit orci. Nam nisl ipsum, auctor vel risus eu, venenatis pulvinar erat.', 100, 10, 3, 10, 'Y', 10, 'Y', 3, 15, 'Y', TO_DATE('2017-12-01 18:12:29', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2015-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (1, 'Actuary', 'Replace indwelling cath', 97, 10, 3, 10, 'Y', 7, 'Y', 1, 7, 'Y', TO_DATE('2017-10-04 11:41:09', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-23 05:40:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (2, 'Programmer Analyst II', 'Grp therap psychsex dysf', 79, 9, 4, 10, 'Y', 1, 'Y', 2, 18, 'Y', TO_DATE('2017-10-12 06:26:03', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-03 11:25:17', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (3, 'Design Engineer', 'Reattach amputated ear', 77, 9, 4, 7, 'Y', 32, 'N', 2, 0, 'Y', TO_DATE('2017-11-18 06:14:02', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-21 04:48:18', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (4, 'Nuclear Power Engineer', 'Closure uterine fistula', 79, 9, 4, 7, 'N', 20, 'N', 4, 17, 'N', TO_DATE('2017-10-28 19:44:01', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-11 11:34:54', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (5, 'Developer IV', 'Tibia/fibula div NEC', 60, 5, 4, 9, 'N', 30, 'Y', 3, 16, 'Y', TO_DATE('2017-10-28 15:45:48', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-20 00:38:22', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (6, 'Assistant Media Planner', 'Insert subq anal stimul', 72, 10, 2, 7, 'N', 28, 'N', 4, 19, 'N', TO_DATE('2017-11-06 14:03:00', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-23 02:31:34', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (7, 'Sales Associate', 'Esophagostomy NOS', 90, 10, 2, 10, 'Y', 28, 'N', 3, 22, 'N', TO_DATE('2017-11-25 01:57:01', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-08 16:03:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (8, 'Engineer I', 'Parasitology-lower resp', 83, 3, 2, 10, 'Y', 37, 'N', 3, 10, 'N', TO_DATE('2017-11-27 22:11:18', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-02 19:53:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (9, 'Budget/Accounting Analyst III', 'Periph nerve incis NEC', 72, 1, 3, 10, 'N', 42, 'N', 3, 18, 'P', TO_DATE('2017-10-24 19:50:55', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-21 20:55:43', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (10, 'Social Worker', 'Transplant of intestine', 61, 5, 1, 10, 'Y', 35, 'Y', 3, 21, 'N', TO_DATE('2017-11-15 04:00:41', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-07 20:10:14', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (11, 'Administrative Officer', 'Insert antimicrobial env', 62, 4, 3, 5, 'Y', 44, 'N', 1, 19, 'N', TO_DATE('2017-10-12 08:43:07', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-23 20:43:47', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (12, 'Geologist II', 'Other fetal monitoring', 99, 3, 2, 8, 'Y', 20, 'N', 4, 15, 'P', TO_DATE('2017-11-22 07:27:50', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-12 11:22:41', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (13, 'Mechanical Systems Engineer', 'Replace trac/laryn stent', 81, 8, 4, 8, 'N', 14, 'Y', 1, 19, 'P', TO_DATE('2017-10-15 22:34:12', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-13 13:26:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (14, 'Information Systems Manager', 'Thorac sm bowel interpos', 98, 6, 2, 5, 'N', 11, 'N', 4, 4, 'N', TO_DATE('2017-11-08 23:57:21', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-18 03:44:45', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (15, 'Desktop Support Technician', 'Cystostomy closure', 63, 9, 2, 6, 'N', 45, 'Y', 3, 10, 'N', TO_DATE('2017-10-18 06:03:27', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-15 04:21:04', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (16, 'Safety Technician I', 'Ins nondrug elut cor st', 90, 3, 4, 10, 'N', 7, 'N', 2, 24, 'N', TO_DATE('2017-11-13 23:58:03', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-22 11:53:25', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (17, 'Marketing Manager', 'Esoph fistula repair NEC', 60, 1, 2, 8, 'Y', 4, 'N', 3, 14, 'Y', TO_DATE('2017-10-09 09:44:29', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-30 16:58:37', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (18, 'Analyst Programmer', 'Fallopian tube biopsy', 79, 3, 3, 6, 'N', 7, 'Y', 2, 5, 'P', TO_DATE('2017-11-14 07:25:43', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-02 19:18:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (19, 'Product Engineer', 'Gastric operation NEC', 91, 10, 2, 5, 'N', 23, 'N', 2, 13, 'Y', TO_DATE('2017-10-31 16:07:51', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-05 13:42:48', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (20, 'Human Resources Assistant III', 'Metacar/car division NEC', 96, 3, 2, 5, 'Y', 2, 'Y', 3, 3, 'N', TO_DATE('2017-10-12 15:49:07', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-23 10:39:16', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (21, 'Media Manager IV', 'Coreoplasty', 96, 1, 3, 10, 'N', 33, 'Y', 1, 25, 'N', TO_DATE('2017-11-09 06:03:38', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-10 15:28:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (22, 'Information Systems Manager', 'Open reduction-finger fx', 95, 9, 2, 10, 'Y', 16, 'N', 3, 20, 'P', TO_DATE('2017-10-22 07:43:33', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-04 20:02:23', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (23, 'Pharmacist', 'In aliquet aliquam posuere. Aliquam vitae ex nisl. Pellentesque sollicitudin nisl vitae nunc gravida consectetur. Vivamus lacus lectus, condimentum vel urna vel, congue commodo dui. Sed eu tempor elit, et pharetra augue. Vestibulum enim enim, cursus vel velit quis, condimentum placerat libero. Vestibulum posuere imperdiet cursus. Nunc ac diam lectus. Nulla vitae nisl purus.', 100, 9, 4, 6, 'Y', 25, 'N', 3, 22, 'Y', TO_DATE('2017-12-04 21:52:41', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-05 23:18:55', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (24, 'Sales Representative', 'Lap sigmoidectomy', 63, 2, 4, 10, 'N', 23, 'N', 4, 15, 'Y', TO_DATE('2017-10-20 14:55:50', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-22 03:56:46', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (25, 'Help Desk Operator', 'Chest cage sequestrec', 60, 2, 4, 7, 'N', 48, 'N', 2, 25, 'N', TO_DATE('2017-10-04 10:16:50', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-26 15:25:52', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (26, 'Community Outreach Specialist', 'Pituitary fossa explorat', 68, 4, 3, 5, 'N', 3, 'Y', 3, 12, 'Y', TO_DATE('2017-11-01 16:01:16', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-12 02:34:42', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (27, 'Help Desk Operator', 'Partial salpingectom NEC', 87, 9, 1, 10, 'Y', 39, 'N', 4, 18, 'P', TO_DATE('2017-11-20 23:07:15', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-22 08:54:30', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (28, 'Help Desk Technician', 'Incision of nose', 87, 9, 2, 9, 'Y', 36, 'N', 2, 19, 'Y', TO_DATE('2017-11-04 16:20:20', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-14 12:18:15', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (29, 'Structural Analysis Engineer', 'Remov abdom wall suture', 96, 10, 1, 6, 'N', 40, 'N', 2, 2, 'N', TO_DATE('2017-11-10 17:18:39', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-09 12:38:04', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (30, 'Accountant IV', 'Gum or alveolar incision', 95, 3, 2, 6, 'Y', 24, 'N', 1, 1, 'N', TO_DATE('2017-11-01 17:21:29', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-06 09:46:56', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (31, 'VP Quality Control', 'Parasitology-lower GI', 98, 5, 4, 8, 'Y', 50, 'N', 2, 5, 'N', TO_DATE('2017-10-13 18:12:21', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-27 01:24:31', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (32, 'VP Accounting', 'Pressurized treat graft', 62, 7, 4, 7, 'N', 26, 'Y', 2, 13, 'Y', TO_DATE('2017-11-18 21:01:50', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-03 06:16:09', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (33, 'Programmer Analyst IV', 'Skel xray-lower limb NOS', 69, 6, 4, 10, 'N', 29, 'Y', 3, 16, 'P', TO_DATE('2017-11-08 23:05:50', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-18 17:03:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (34, 'Editor', 'Magnet remove FB lens', 87, 3, 1, 10, 'Y', 21, 'Y', 2, 2, 'Y', TO_DATE('2017-11-26 01:24:52', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-07 21:35:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (35, 'Chemical Engineer', 'Revise disc prosth NOS', 60, 5, 2, 9, 'N', 5, 'N', 2, 0, 'Y', TO_DATE('2017-10-22 13:03:47', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-01 21:32:36', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (36, 'Executive Secretary', 'Remove cervical cerclage', 89, 10, 1, 10, 'N', 47, 'Y', 2, 26, 'N', TO_DATE('2017-10-09 23:47:59', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-13 21:09:20', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (37, 'Product Engineer', 'Removal spine stim lead', 67, 7, 1, 8, 'N', 34, 'N', 2, 12, 'N', TO_DATE('2017-10-27 08:58:36', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-01 12:56:37', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (38, 'Editor', 'Suture cord & epid lacer', 63, 2, 3, 7, 'Y', 38, 'Y', 4, 2, 'Y', TO_DATE('2017-10-27 16:11:36', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2017-12-09 01:16:35', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (39, 'Quality Engineer', 'Thermcaut scler w iridec', 86, 3, 4, 10, 'Y', 14, 'Y', 4, 14, 'N', TO_DATE('2017-11-21 09:20:21', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-25 00:35:01', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (40, 'Compensation Analyst', 'Radical vag hyst NEC/NOS', 84, 2, 4, 10, 'Y', 6, 'N', 4, 16, 'Y', TO_DATE('2017-11-15 14:25:53', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2017-12-13 11:24:34', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (41, 'Graphic Designer', 'Retrogr cystourethrogram', 80, 1, 2, 10, 'Y', 19, 'Y', 2, 22, 'Y', TO_DATE('2017-11-03 10:42:05', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-20 10:46:58', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (42, 'Engineer II', 'Elbow arthroplasty NEC', 92, 6, 1, 6, 'N', 47, 'Y', 3, 19, 'P', TO_DATE('2017-10-16 07:24:41', 'YYYY-MM-DD HH24:MI:SS'), 'Y', TO_DATE('2018-01-06 21:43:39', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (43, 'Social Worker', 'Osteoclasis-patella', 70, 10, 3, 9, 'Y', 8, 'Y', 4, 12, 'Y', TO_DATE('2017-10-29 10:35:25', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-08 05:24:38', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "USER_NAME".JOB ("JobID", "Name", "Description", "HrSalary", "HrPerWeek", "MinWeek", "MaxWeek", "IsContinuous", "Quota", "IsReqInterview", "MinStudyYear", "PrefCode", "IsValid", "LastModDate", "IsOpen", "AppDeadline") VALUES (44, 'Technical Writer', 'Hair transplant', 100, 9, 3, 8, 'N', 39, 'Y', 1, 19, 'N', TO_DATE('2017-11-13 19:10:56', 'YYYY-MM-DD HH24:MI:SS'), 'N', TO_DATE('2018-01-19 01:58:51', 'YYYY-MM-DD HH24:MI:SS'));