INSERT INTO "USER_NAME".JOB_SUPERVISE ("JobID", "SupervisorID") VALUES (1, 'dmli');
INSERT INTO "USER_NAME".JOB_SUPERVISE ("JobID", "SupervisorID") VALUES (1, 'dalao');
INSERT INTO "USER_NAME".JOB_SUPERVISE ("JobID", "SupervisorID") VALUES (0, 'cslhf');
INSERT INTO "USER_NAME".JOB_SUPERVISE ("JobID", "SupervisorID") VALUES (0, 'xhwang');
INSERT INTO "USER_NAME".JOB_SUPERVISE ("JobID", "SupervisorID") VALUES (1, 'cslhf');