INSERT INTO "USER_NAME".JOB_MAJOR_REQ ("JobID", "MajorID") VALUES (0, '61431-');
INSERT INTO "USER_NAME".JOB_MAJOR_REQ ("JobID", "MajorID") VALUES (0, '61431-FCS');
INSERT INTO "USER_NAME".JOB_MAJOR_REQ ("JobID", "MajorID") VALUES (0, '61431-FIT');
INSERT INTO "USER_NAME".JOB_MAJOR_REQ ("JobID", "MajorID") VALUES (0, '61431-FIS');