INSERT INTO "USER_NAME".SUPERVISOR ("PersonID", "DeptID") VALUES ('cslhf', 11);
INSERT INTO "USER_NAME".SUPERVISOR ("PersonID", "DeptID") VALUES ('dalao', 18);
INSERT INTO "USER_NAME".SUPERVISOR ("PersonID", "DeptID") VALUES ('cslla', 18);
INSERT INTO "USER_NAME".SUPERVISOR ("PersonID", "DeptID") VALUES ('dmli', 28);
INSERT INTO "USER_NAME".SUPERVISOR ("PersonID", "DeptID") VALUES ('xhwang', 11);